In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X = iris.data

In [7]:
y = iris.target

In [8]:
#OneHotEncode the classification numbers
from keras.utils import to_categorical

In [9]:
y = to_categorical(y)

In [11]:
y.shape

(150, 3)

In [12]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [13]:
#split train and test
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [16]:
#Scale values (standardization)
from sklearn.preprocessing import MinMaxScaler

In [17]:
scaler_object = MinMaxScaler()

In [18]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [19]:
scaled_X_train = scaler_object.transform(X_train)

In [20]:
scaled_X_test = scaler_object.transform(X_test)

In [21]:
#Creating the Neural Network
from keras.models import Sequential
from keras.layers import Dense

In [23]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [24]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Epoch 1/150
 - 0s - loss: 0.3322 - accuracy: 0.9400
Epoch 2/150
 - 0s - loss: 0.3294 - accuracy: 0.9300
Epoch 3/150
 - 0s - loss: 0.3279 - accuracy: 0.9400
Epoch 4/150
 - 0s - loss: 0.3262 - accuracy: 0.9400
Epoch 5/150
 - 0s - loss: 0.3247 - accuracy: 0.9400
Epoch 6/150
 - 0s - loss: 0.3236 - accuracy: 0.9200
Epoch 7/150
 - 0s - loss: 0.3228 - accuracy: 0.9200
Epoch 8/150
 - 0s - loss: 0.3205 - accuracy: 0.9200
Epoch 9/150
 - 0s - loss: 0.3184 - accuracy: 0.9400
Epoch 10/150
 - 0s - loss: 0.3161 - accuracy: 0.9400
Epoch 11/150
 - 0s - loss: 0.3142 - accuracy: 0.9400
Epoch 12/150
 - 0s - loss: 0.3130 - accuracy: 0.9400
Epoch 13/150
 - 0s - loss: 0.3117 - accuracy: 0.9400
Epoch 14/150
 - 0s - loss: 0.3098 - accuracy: 0.9400
Epoch 15/150
 - 0s - loss: 0.3083 - accuracy: 0.9400
Epoch 16/150
 - 0s - loss: 0.3068 - accuracy: 0.9400
Epoch 17/150
 - 0s - loss: 0.3053 - accuracy: 0.9400
Epoch 18/150
 - 0s - loss: 0.3048 - accuracy: 0.9400
Epoch 19/150
 - 0s - loss: 0.3047 - accuracy: 0.9400
Ep

In [28]:
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)

In [29]:
predictions = model.predict_classes(scaled_X_test)

In [32]:
target_results = y_test.argmax(axis=1)

In [33]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [35]:
print(confusion_matrix(target_results, predictions))

[[19  0  0]
 [ 0 14  1]
 [ 0  1 15]]


In [36]:
print(classification_report(target_results, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

   micro avg       0.96      0.96      0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [37]:
print(accuracy_score(target_results, predictions))

0.96


In [38]:
model.save('myfirstmodel.h5')

In [39]:
from keras.models import load_model

In [40]:
new_model = load_model('myfirstmodel.h5')

In [41]:
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)